services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d20dcjp5pdvs73cdvs80-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: thesis_db_dtvo
      - key: DB_USERNAME
        value: thesis_db_dtvo_user
      - key: DB_PASSWORD
        value: pflTm2bEK3UBgQQTHq6oxQ6B0gLteTQp
    startCommand: |
      php artisan config:clear
      php artisan cache:clear
      php artisan config:cache
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=10000
